config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  post 'auth/:provider', to: 'web/auth#request', as: :auth_request
  get 'auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth
  delete 'auth', to: 'web/auth#destroy', as: :sign_out

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :web do
    root 'home#index'
    get '/registration', to: 'registration#index', as: :new_user_registration

    resources :bulletins, except: :destroy do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    namespace 'admin', as: 'admin' do
      root 'bulletins#index'

      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories
      resources :users, except: %i[create show new]
    end

    scope 'profile' do
      root 'profile/home#index', as: :profile
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# class ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user, dependent: :destroy
  belongs_to :category, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :title, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, presence: true, content_type: %i[png jpg jpeg], size: { less_than: 5.megabytes }

  default_scope { order('created_at DESC') }

  paginates_per 20

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published], to: :archived
    end

    event :to_draft do
      transitions from: %i[draft under_moderation published], to: :draft
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  paginates_per 20
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true

  paginates_per 20

  def full_name
    name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_management.rb
# frozen_string_literal: true

module AuthManagement
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    reset_session
    redirect_to root_path
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_signed_in_user!
    return if current_user

    redirect_to root_path
  end

  def require_admin!
    return if current_user&.admin?

    redirect_to root_path, alert: t('layouts.web.admin.flash.admins_only')
  end

  def user_not_authorized
    redirect_to root_path, alert: t('notice.auth.not_authorized')
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  helper_method :signed_in?, :sign_out

  include AuthManagement
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    auth_user_info = auth[:info]

    user = User.find_or_initialize_by(email: auth_user_info[:email].downcase)
    user.name = auth_user_info[:name]

    if user.save
      sign_in user
      redirect_to root_path, notice: t('notice.auth.sign_in')
    else
      redirect_to new_user_registration_url
    end
  end

  def destroy
    sign_out
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  helper_method :resource_bulletin

  def index
    @query = Bulletin.published.ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end

  def new
    @bulletin = Bulletin.new
    @categories = Category.all

    authorize Bulletin
  end

  def create
    authorize Bulletin

    if current_user.bulletins.create!(bulletin_params)
      redirect_to profile_path, notice: t('notice.bulletins.created')
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize resource_bulletin
  end

  def update
    authorize resource_bulletin

    if resource_bulletin.update(bulletin_params)
      redirect_to profile_path, notice: t('notice.bulletins.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def to_moderate
    authorize resource_bulletin

    resource_bulletin.to_moderate!
    redirect_to profile_path, notice: t('notice.bulletins.to_moderation')
  end

  def archive
    authorize resource_bulletin

    resource_bulletin.archive!
    redirect_to profile_path, notice: t('notice.bulletins.archived')
  end

  private

  def bulletin_params
    params.require(:bulletin).permit(:title, :description, :category_id, :image)
  end

  def resource_bulletin
    @resource_bulletin ||= Bulletin.find(params[:id])
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index
    @query = Bulletin.published.ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end
end

app/controllers/web/registration_controller.rb
# frozen_string_literal: true

class Web::RegistrationController < Web::ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# module ApplicationHelper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/web/admin/home_helper.rb
# frozen_string_literal: true

module Web::Admin::HomeHelper
end

app/helpers/web/admin/users_helper.rb
# frozen_string_literal: true

module Web::Admin::UsersHelper
end

app/helpers/web/auth_helper.rb
# frozen_string_literal: true

module Web::AuthHelper
end

app/helpers/web/bulletins_helper.rb
# frozen_string_literal: true

module Web::BulletinsHelper
end

app/helpers/web/omniauth_callbacks_helper.rb
# frozen_string_literal: true

module Web::OmniauthCallbacksHelper
end

app/helpers/web/registration_helper.rb
# frozen_string_literal: true

module Web::RegistrationHelper
end

app/helpers/web/users_helper.rb
# frozen_string_literal: true

module Web::UsersHelper
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_navigation.html.slim
nav.navbar.navbar-static-top.navbar-expand-md
  .container-fluid
    button.navbar-toggler.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
      span.sr-only Toggle navigation
    = link_to root_path, class: 'navbar-brand link-dark' do
      = t('.logo')
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.me-auto
        li.nav.navbar-nav
          = link_to t('.bulletins'), root_path, class: 'nav-link link-dark'
        - if signed_in?
          li.nav.navbar-nav
            = link_to t('.add_bulletin'), new_bulletin_path, class: 'nav-link link-dark'
          li.nav.navbar-nav
            = link_to t('.my_bulletins'), profile_path, class: 'nav-link link-dark'
      ul.nav.navbar-nav.ms-auto
        - if signed_in?
          - if policy(:dashboard).show?
            li.nav-item
              = link_to 'Admin', admin_root_path, class: 'nav-link link-dark'
          li.nav-item
            = link_to t('actions.sign_out'), sign_out_path, method: :delete, class: 'nav-link link-dark'
        - else
          li.nav-item
            = link_to t('actions.sign_in'), auth_request_path('github'), method: :post, class: 'nav-link link-dark'
          li.nav-item
            = link_to t('actions.sign_up'), new_user_registration_path, class: 'nav-link link-dark'
.container-fluid
  hr.w-100.border-1.border-top.border-dark.mt-1

app/views/layouts/web/admin/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : 'Bulletin'
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-light
    header
      = render 'layouts/shared/navigation'
    = render 'layouts/shared/flash'
    main.my-5[role="main"]
      .container-xl
        .card.p-3.p-md-4.p-lg-5.card-body.border-0.shadow
          = content_for?(:content) ? yield(:content) : yield

app/views/layouts/web/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : 'Bulletin'
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-light
    header
      = render 'layouts/shared/navigation'
    = render 'layouts/shared/flash'
    main.my-5[role="main"]
      .container-xl
        .card.p-3.p-md-4.p-lg-5.card-body.border-0.shadow
          = content_for?(:content) ? yield(:content) : yield

app/views/web/shared/_page_title.html.slim
h2 = title
hr.mb-4

app/views/web/shared/_search_form.html.slim
.bg-light.p-3.p-md-4.mb-4
  = search_form_for @query, { url: url, class: 'row g-3' } do |f|
    .col-sm-7.col-md-auto.flex-md-grow-1
      = f.search_field :title_cont, class: 'form-control'
      small.form-text.text-muted = t('.bulletin_details')
    .col-sm-5.col-md-4
      = f.collection_select :category_id_eq, Category.all, :id, :name, { include_blank: true }, { class: 'form-control' }
      small.form-text.text-muted = t('.category_details')
    .col-md-auto
      .row.g-1
        .col-auto
          = f.submit({ class: 'btn btn-primary' })
        .col-auto
          = link_to t('actions.reset'), url, class: 'btn btn-outline-primary'