config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  post 'auth/:provider', to: 'web/auth#request', as: :auth_request
  get 'auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth
  delete 'auth', to: 'web/auth#destroy', as: :sign_out

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :web do
    root 'home#index'
    get '/registration', to: 'registration#index', as: :new_user_registration

    resources :bulletins, except: :destroy do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    namespace 'admin', as: 'admin' do
      root 'bulletins#index'

      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories
      resources :users, except: %i[create show new]
    end

    scope 'profile' do
      root 'profile/home#index', as: :profile
    end
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

class Web::Admin::HomeController < Web::Admin::ApplicationController
  def index; end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index
    @query = Bulletin.published.ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end
end

app/controllers/web/profile/application_controller.rb
# frozen_string_literal: true

class Web::Profile::ApplicationController < Web::ApplicationController
  before_action :require_signed_in_user!
end

app/controllers/web/profile/home_controller.rb
# frozen_string_literal: true

class Web::Profile::HomeController < Web::Profile::ApplicationController
  def index
    @bulletins = current_user.bulletins.page params[:page]
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/web/admin/home_helper.rb
# frozen_string_literal: true

module Web::Admin::HomeHelper
end

app/helpers/web/profile/home_helper.rb
# frozen_string_literal: true

module Web::Profile::HomeHelper
end

app/views/web/profile/home/index.html.slim
= render '/web/shared/page_title', title: t('.title')

div
  = link_to t('.add'), new_bulletin_path, class: 'btn btn-primary'

.table-responsive
  table.table.align-middle
    thead
      tr
        th(scope="col") = t('common.table.id')
        th(scope="col") = t('common.table.name')
        th(scope="col") = t('common.table.category')
        th(scope="col") = t('common.table.state')
        th.text-end(scope="col") = t('common.table.actions')
    tbody
      - @bulletins.each do |bulletin|
        tr
          th(scope="row") = bulletin.id
          td = bulletin.title
          td = bulletin.category.name
          td = bulletin.state
          td
            .d-flex.gap-1.justify-content-end
              = link_to t('actions.edit'), edit_bulletin_path(bulletin), class: 'btn btn-sm btn-success'
              - if bulletin.may_to_moderate?
                = link_to t('actions.to_moderate'), to_moderate_bulletin_path(bulletin), method: :patch, class: 'btn btn-sm btn-primary'
              - if bulletin.may_archive?
                = link_to t('actions.archive'), archive_bulletin_path(bulletin), method: :patch, class: 'btn btn-sm btn-danger'
= paginate @bulletins, left: 1, right: 3, theme: 'bootstrap'