config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
  post 'auth/:provider', to: 'web/auth#request', as: :auth_request
  get 'auth/:provider/callback', to: 'web/auth#callback', as: :callback_auth
  delete 'auth', to: 'web/auth#destroy', as: :sign_out

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :web do
    root 'home#index'
    get '/registration', to: 'registration#index', as: :new_user_registration

    resources :bulletins, except: :destroy do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    namespace 'admin', as: 'admin' do
      root 'bulletins#index'

      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories
      resources :users, except: %i[create show new]
    end

    scope 'profile' do
      root 'profile/home#index', as: :profile
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# class ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user, dependent: :destroy
  belongs_to :category, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :title, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, presence: true, content_type: %i[png jpg jpeg], size: { less_than: 5.megabytes }

  default_scope { order('created_at DESC') }

  paginates_per 20

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published], to: :archived
    end

    event :to_draft do
      transitions from: %i[draft under_moderation published], to: :draft
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  paginates_per 20
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true

  paginates_per 20

  def full_name
    name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_management.rb
# frozen_string_literal: true

module AuthManagement
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    reset_session
    redirect_to root_path
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_signed_in_user!
    return if current_user

    redirect_to root_path
  end

  def require_admin!
    return if current_user&.admin?

    redirect_to root_path, alert: t('layouts.web.admin.flash.admins_only')
  end

  def user_not_authorized
    redirect_to root_path, alert: t('notice.auth.not_authorized')
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

class Web::Admin::BulletinsController < Web::Admin::ApplicationController
  def index
    authorize Bulletin

    @query = Bulletin.where.not(state: :draft).ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end

  def publish
    authorize resource
    resource.publish!
    redirect_to admin_root_path, notice: t('notice.bulletins.published')
  end

  def reject
    resource.reject!
    redirect_to admin_root_path, notice: t('notice.bulletins.rejected')
  end

  def archive
    resource.archive!
    redirect_to admin_root_path, notice: t('notice.bulletins.archived')
  end

  private

  def resource
    Bulletin.find(params[:id])
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

class Web::Admin::HomeController < Web::Admin::ApplicationController
  def index; end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  helper_method :signed_in?, :sign_out

  include AuthManagement
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    auth_user_info = auth[:info]

    user = User.find_or_initialize_by(email: auth_user_info[:email].downcase)
    user.name = auth_user_info[:name]

    if user.save
      sign_in user
      redirect_to root_path, notice: t('notice.auth.sign_in')
    else
      redirect_to new_user_registration_url
    end
  end

  def destroy
    sign_out
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

class Web::BulletinsController < Web::ApplicationController
  helper_method :resource_bulletin

  def index
    @query = Bulletin.published.ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end

  def new
    @bulletin = Bulletin.new
    @categories = Category.all

    authorize Bulletin
  end

  def create
    authorize Bulletin

    if current_user.bulletins.create!(bulletin_params)
      redirect_to profile_path, notice: t('notice.bulletins.created')
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize resource_bulletin
  end

  def update
    authorize resource_bulletin

    if resource_bulletin.update(bulletin_params)
      redirect_to profile_path, notice: t('notice.bulletins.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def to_moderate
    authorize resource_bulletin

    resource_bulletin.to_moderate!
    redirect_to profile_path, notice: t('notice.bulletins.to_moderation')
  end

  def archive
    authorize resource_bulletin

    resource_bulletin.archive!
    redirect_to profile_path, notice: t('notice.bulletins.archived')
  end

  private

  def bulletin_params
    params.require(:bulletin).permit(:title, :description, :category_id, :image)
  end

  def resource_bulletin
    @resource_bulletin ||= Bulletin.find(params[:id])
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index
    @query = Bulletin.published.ransack(params[:q])
    @bulletins = @query.result(distinct: true).page params[:page]
  end
end

app/controllers/web/registration_controller.rb
# frozen_string_literal: true

class Web::RegistrationController < Web::ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# module ApplicationHelper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/web/admin/bulletins_helper.rb
# frozen_string_literal: true

module Web::Admin::BulletinsHelper
end

app/helpers/web/admin/categories_helper.rb
# frozen_string_literal: true

module Web::Admin::CategoriesHelper
end

app/helpers/web/admin/home_helper.rb
# frozen_string_literal: true

module Web::Admin::HomeHelper
end

app/helpers/web/admin/users_helper.rb
# frozen_string_literal: true

module Web::Admin::UsersHelper
end

app/helpers/web/auth_helper.rb
# frozen_string_literal: true

module Web::AuthHelper
end

app/helpers/web/bulletins_helper.rb
# frozen_string_literal: true

module Web::BulletinsHelper
end

app/helpers/web/omniauth_callbacks_helper.rb
# frozen_string_literal: true

module Web::OmniauthCallbacksHelper
end

app/helpers/web/profile/home_helper.rb
# frozen_string_literal: true

module Web::Profile::HomeHelper
end

app/helpers/web/registration_helper.rb
# frozen_string_literal: true

module Web::RegistrationHelper
end

app/helpers/web/users_helper.rb
# frozen_string_literal: true

module Web::UsersHelper
end

app/views/web/admin/bulletins/index.html.slim
= render layout: '/web/admin/shared/dashboard', locals: { active: 'bulletins', title: t('web.admin.bulletins.title') } do
  = render '/web/shared/search_form', url: admin_bulletins_path

  table.table
    thead
      tr
        th(scope="col") = t('common.table.id')
        th(scope="col") = t('common.table.title')
        th(scope="col") = t('common.table.category')
        th(scope="col") = t('common.table.state')
        th.text-end(scope="col") = t('common.table.actions')
    tbody
      - @bulletins.each do |bulletin|
        tr
          th(scope="row") = bulletin.id
          td = bulletin.title
          td = bulletin.category.name
          td = bulletin.state
          td: .d-flex.gap-1.justify-content-end
            - if bulletin.may_publish?
              = link_to t('actions.approve'), publish_admin_bulletin_path(bulletin), method: :patch, class: 'btn btn-sm btn-primary'
            - if bulletin.may_reject?
              = link_to t('actions.reject'), reject_admin_bulletin_path(bulletin), method: :patch, class: 'btn btn-sm btn-danger'
            - if bulletin.may_archive?
              = link_to t('actions.archive'), archive_admin_bulletin_path(bulletin), method: :patch, class: 'btn btn-sm btn-secondary'
  = paginate @bulletins, left: 1, right: 3, theme: 'bootstrap'

app/views/web/bulletins/_form.html.slim
= simple_form_for bulletin do |f|
  = f.input :title, wrapper_html: { class: 'mb-3' }
  = f.input :description, as: :text, wrapper_html: { class: 'mb-3' }
  = f.association :category, wrapper_html: { class: 'mb-3' }
  - if bulletin.image_attachment
    = image_tag bulletin.image, class: 'img-thumbnail mb-2'
  = f.input :image, as: :file, accept: 'image/png, image/gif, image/jpeg', input_html: { class: 'form-control' }

  .mt-5
    = link_to t('actions.cancel'), profile_path, class: 'btn btn-secondary me-1'
    = f.submit t('actions.save'), class: 'btn btn-primary'

app/views/web/bulletins/edit.html.slim
= render '/web/shared/page_title', title: t('.title')

= render 'form', bulletin: resource_bulletin

app/views/web/bulletins/index.html.slim
= render '/web/shared/page_title', title: t('.title')

= render '/web/shared/search_form', url: bulletins_path

.row.g-4
  - @bulletins.each do |bulletin|
    .col-12.col-sm-6.col-md-4.col-lg-3: .card
      = image_tag bulletin.image, class: 'card-img-top'
      .card-body
        h4.card-title
          = link_to bulletin.title, bulletin_path(bulletin)
        = distance_of_time_in_words(bulletin.created_at, Time.current)

app/views/web/bulletins/new.html.slim
= render '/web/shared/page_title', title: t('.title')

= render 'form', bulletin: @bulletin

app/views/web/bulletins/show.html.slim
= render '/web/shared/page_title', title: resource_bulletin.title

.row
  .col-md-6
    = image_tag resource_bulletin.image, class: 'img-thumbnail mb-4'
    p = resource_bulletin.description
  .col-md-6
    .card.card-body
      = resource_bulletin.user.full_name